name: Deploy to GH pages

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install Dependencies
        run: |
          npm i git+https://github.com/AsbertMa/app-hub.git#gh-pages
          npm ci
  
      - name: Build Website
        run: npm run build

      - name: Deploy To GH Pages

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          force_orphan: true